run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - prealloc
    - unconvert
    - whitespace
    - nolintlint
  disable:
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - experimental
    disabled-checks:
      - paramTypeCombine
  staticcheck:
    checks:
      - all
      - -SA1019
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
    - path: internal/colors/colors.go
      text: "WhyNoLint"
      linters:
        - staticcheck
